parameters = {
    "p00004": "Stream width, feet",
    "p00010": "Temperature, degrees Celsius",
    "p00020": "Temperature, air, degrees Celsius",
    "p00061": "Discharge, instantaneous, cubic feet per second",
    "p00063": "Number of sampling points, count",
    "p00095": "Specific conductance, unfiltered, uS/centimeter",
    "p00191": "Hydrogen ion, unfiltered, calculated, mg/L",
    "p00400": "pH, unfiltered, field",
    "p00403": "pH, unfiltered, laboratory",
    "p00405": "Carbon dioxide, unfiltered, mg/L",
    "p00681": "Organic carbon, filtered, mg/L",
    "p00900": "Hardness, mg/L as calcium carbonate",
    "p00905": "Noncarbonate hardness, filtered, lab, mg/L as calcium carbonate",
    "p00915": "Calcium, filtered, mg/L",
    "p00925": "Magnesium, filtered, mg/L",
    "p00930": "Sodium, filtered, mg/L",
    "p00931": "Sodium adsorption ratio (SAR), number",
    "p00932": "Sodium fraction of cations, percent in equivalents of major cations",
    "p00935": "Potassium, filtered, mg/L",
    "p00940": "Chloride, filtered, mg/L",
    "p00945": "Sulfate, filtered, mg/L",
    "p00950": "Fluoride, filtered, mg/L",
    "p00955": "Silica, filtered, mg/L as SiO2",
    "p01000": "Arsenic, filtered, micrograms per liter",
    "p01002": "Arsenic, unfiltered, micrograms per liter",
    "p01025": "Cadmium, filtered, micrograms per liter",
    "p01027": "Cadmium, unfiltered, micrograms per liter",
    "p01040": "Copper, filtered, micrograms per liter",
    "p01042": "Copper, unfiltered, recoverable, micrograms per liter",
    "p01045": "Iron, unfiltered, recoverable, micrograms per liter",
    "p01046": "Iron, filtered, micrograms per liter",
    "p01049": "Lead, filtered, micrograms per liter",
    "p01051": "Lead, unfiltered, recoverable, micrograms per liter",
    "p01055": "Manganese, unfiltered, recoverable, micrograms per liter",
    "p01056": "Manganese, filtered, micrograms per liter",
    "p01090": "Zinc, filtered, micrograms per liter",
    "p01092": "Zinc, unfiltered, recoverable, micrograms per liter",
    "p29801": "Alkalinity, filtered, fixed endpoint (pH 4.5) titration, laboratory, mg/L as calcium carbonate",
    "p30209": "Discharge, instantaneous, cubic meters per second",
    "p50015": "Transit rate, sampler, feet per second",
    "p50280": "Site visit purpose, code",
    "p63676": "Turbidity, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiometric correction, NTRU",
    "p70301": "Dissolved solids, filtered, sum of constituents, mg/L",
    "p70302": "Dissolved solids, short tons per day",
    "p70303": "Dissolved solids, filtered, short tons per acre-foot",
    "p70331": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters",
    "p72219": "Sampler nozzle material, code",
    "p72220": "Sampler nozzle diameter, code",
    "p80154": "Suspended sediment concentration, mg/L",
    "p80155": "Suspended sediment discharge, short tons per day",
    "p82398": "Sampling method, code",
    "p84164": "Sampler type, code",
    "p84171": "Sample splitter type, field, code",
    "p84182": "Bottle or bag sampler material (construction), code",
    "p90095": "Specific conductance, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius",
    "p91157": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams",
    "p91165": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams",
    "p99105": "Type of replicate, code",
    "p99111": "Type of quality assurance data associated with sample, code",
    "p99156": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD",
    "p99159": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD",
    "p99161": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD",
    "p99163": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD",
    "p99164": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD",
    "p99171": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD",
    "p99172": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD",
    "p99173": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD",
    "p99206": "NWIS lot number, capsule filter, 0.45 micron",
    "p99870": "Julian date, in-bottle digestion, ddd",
}

param_labels = [
    # {"label": "Stream width, feet", "value": "p00004"},
    # {"label": "Temperature, degrees Celsius", "value": "p00010"},
    # {"label": "Temperature, air, degrees Celsius", "value": "p00020"},
    # {"label": "Discharge, instantaneous, cubic feet per second", "value": "p00061"},
    # {"label": "Number of sampling points, count", "value": "p00063"},
    {"label": "Specific conductance, unfiltered", "value": "p00095"},
    # {"label": "Hydrogen ion, unfiltered, calculated, mg/L", "value": "p00191"},
    {"label": "pH, unfiltered", "value": "p00400"},
    # {"label": "pH, unfiltered, laboratory, standard units", "value": "p00403"},
    # {"label": "Carbon dioxide, unfiltered, mg/L", "value": "p00405"},
    # {"label": "Organic carbon, filtered, mg/L", "value": "p00681"},
    # {"label": "Hardness, mg/L as calcium carbonate", "value": "p00900"},
    # {"label": "Noncarbonate hardness, filtered, lab, mg/L as calcium carbonate", "value": "p00905"},
    {"label": "Calcium, filtered, mg/L", "value": "p00915"},
    {"label": "Magnesium, filtered, mg/L", "value": "p00925"},
    {"label": "Sodium, filtered, mg/L", "value": "p00930"},
    # {"label": "Sodium adsorption ratio (SAR), number", "value": "p00931"},
    # {"label": "Sodium fraction of cations, percent in equivalents of major cations", "value": "p00932"},
    {"label": "Potassium, filtered, mg/L", "value": "p00935"},
    {"label": "Chloride, filtered, mg/L", "value": "p00940"},
    # {"label": "Sulfate, filtered, mg/L", "value": "p00945"},
    # {"label": "Fluoride, filtered, mg/L", "value": "p00950"},
    # {"label": "Silica, filtered, mg/L as SiO2", "value": "p00955"},
    # {"label": "Arsenic, filtered, micrograms per liter", "value": "p01000"},
    # {"label": "Arsenic, unfiltered, micrograms per liter", "value": "p01002"},
    # {"label": "Cadmium, filtered, micrograms per liter", "value": "p01025"},
    # {"label": "Cadmium, unfiltered, micrograms per liter", "value": "p01027"},
    # {"label": "Copper, filtered, micrograms per liter", "value": "p01040"},
    # {"label": "Copper, unfiltered, recoverable, micrograms per liter", "value": "p01042"},
    {"label": "Iron, unfiltered, recoverable, mg/L", "value": "p01045"},
    {"label": "Iron, filtered, mg/L", "value": "p01046"},
    # {"label": "Lead, filtered, micrograms per liter", "value": "p01049"},
    # {"label": "Lead, unfiltered, recoverable, micrograms per liter", "value": "p01051"},
    # {"label": "Manganese, unfiltered, recoverable, micrograms per liter", "value": "p01055"},
    # {"label": "Manganese, filtered, micrograms per liter", "value": "p01056"},
    # {"label": "Zinc, filtered, micrograms per liter", "value": "p01090"},
    # {"label": "Zinc, unfiltered, recoverable, micrograms per liter", "value": "p01092"},
    # {"label": "Alkalinity, filtered, fixed endpoint (pH 4.5) titration, laboratory, mg/L as calcium carbonate", "value": "p29801"},
    # {"label": "Discharge, instantaneous, cubic meters per second", "value": "p30209"},
    # {"label": "Transit rate, sampler, feet per second", "value": "p50015"},
    # {"label": "Site visit purpose, code", "value": "p50280"},
    # {"label": "Turbidity, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiom", "value": "p63676"},
    # {"label": "Dissolved solids, filtered, sum of constituents, mg/L", "value": "p70301"},
    # {"label": "Dissolved solids, short tons per day", "value": "p70302"},
    # {"label": "Dissolved solids, filtered, short tons per acre-foot", "value": "p70303"},
    # {"label": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters", "value": "p70331"},
    # Keep from here above
    # {"label": "Sampler nozzle material, code", "value": "p72219"},
    # {"label": "Sampler nozzle diameter, code", "value": "p72220"},
    # {"label": "Suspended sediment concentration, mg/L", "value": "p80154"},
    # {"label": "Suspended sediment discharge, short tons per day", "value": "p80155"},
    # {"label": "Sampling method, code", "value": "p82398"},
    # {"label": "Sampler type, code", "value": "p84164"},
    # {"label": "Sample splitter type, field, code", "value": "p84171"},
    # {"label": "Bottle or bag sampler material (construction), code", "value": "p84182"},
    # {"label": "Specific conductance, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius", "value": "p90095"},
    # {"label": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams", "value": "p91157"},
    # {"label": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams", "value": "p91165"},
    # {"label": "Type of replicate, code", "value": "p99105"},
    # {"label": "Type of quality assurance data associated with sample, code", "value": "p99111"},
    # {"label": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD", "value": "p99156"},
    # {"label": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD", "value": "p99159"},
    # {"label": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD", "value": "p99161"},
    # {"label": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD", "value": "p99163"},
    # {"label": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD", "value": "p99164"},
    # {"label": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD", "value": "p99171"},
    # {"label": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD", "value": "p99172"},
    # {"label": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD", "value": "p99173"},
    # {"label": "NWIS lot number, capsule filter, 0.45 micron", "value": "p99206"},
    # {"label": "Julian date, in-bottle digestion, ddd", "value": "p99870"},
]

sample_codes = [
    {"label": "Regular", "value": "9"},
    {"label": "Blank", "value": "2"},
    {"label": "Spike", "value": "1"},
    {"label": "Replicate", "value": "7"},
    {"label": "Reference", "value": "3"},
    {"label": "Blind", "value": "4"},
    {"label": "Duplicate", "value": "5"},
    {"label": "Reference material", "value": "6"},
    {"label": "Spike solution", "value": "8"},
    {"label": "Not determined", "value": "A"},
    {"label": "Other QA", "value": "B"},
    {"label": "Composite (time)", "value": "H"},
    {"label": "Spike Replicate", "value": "K"},
    {"label": "Profile", "value": "P"},
]

station_list = [
    "USGS-433615110440001",
    "USGS-433604110443401",
    "USGS-433604110443402",
    "USGS-433604110443403",
    "USGS-433551110443501",
    "USGS-433600110443701",
    "USGS-433603110443501",
    "USGS-433603110443502",
    "USGS-433605110443801",
    "USGS-433613110443501",
    "USGS-433641110441501",
    "USGS-433630110442701",
    "USGS-433556110441601",
    "USGS-433558110441501",
    "USGS-433605110441201",
    "USGS-433602110441201",
    "USGS-433604110441001",
    "USGS-433607110440901",
    "USGS-433556110441501",
    "USGS-433606110440501",
]

access_level_codes = [
    {"label": "0-Public", "value": "0"},
    {"label": "1-Coop", "value": "1"},
    {"label": "2-USGS", "value": "2"},
]

# {
#     "p00004": "Stream width, feet",
#     "p00010": "Temperature, degrees Celsius",
#     "p00020": "Temperature, air, degrees Celsius",
#     "p00061": "Discharge, instantaneous, cubic feet per second",
#     "p00063": "Number of sampling points, count",
#     "p00095": "Specific conductance, unfiltered, microsiemens per centimeter at 25 degrees Celsius",
#     "p00191": "Hydrogen ion, unfiltered, calculated, mg/L",
#     "p00400": "pH, unfiltered, field, standard units",
#     "p00403": "pH, unfiltered, laboratory, standard units",
#     "p00405": "Carbon dioxide, unfiltered, mg/L",
#     "p00681": "Organic carbon, filtered, mg/L",
#     "p00900": "Hardness, mg/L as calcium carbonate",
#     "p00905": "Noncarbonate hardness, filtered, lab, mg/L as calcium carbonate",
#     "p00915": "Calcium, filtered, mg/L",
#     "p00925": "Magnesium, filtered, mg/L",
#     "p00930": "Sodium, filtered, mg/L",
#     "p00931": "Sodium adsorption ratio (SAR), number",
#     "p00932": "Sodium fraction of cations, percent in equivalents of major cations",
#     "p00935": "Potassium, filtered, mg/L",
#     "p00940": "Chloride, filtered, mg/L",
#     "p00945": "Sulfate, filtered, mg/L",
#     "p00950": "Fluoride, filtered, mg/L",
#     "p00955": "Silica, filtered, mg/L as SiO2",
#     "p01000": "Arsenic, filtered, micrograms per liter",
#     "p01002": "Arsenic, unfiltered, micrograms per liter",
#     "p01025": "Cadmium, filtered, micrograms per liter",
#     "p01027": "Cadmium, unfiltered, micrograms per liter",
#     "p01040": "Copper, filtered, micrograms per liter",
#     "p01042": "Copper, unfiltered, recoverable, micrograms per liter",
#     "p01045": "Iron, unfiltered, recoverable, micrograms per liter",
#     "p01046": "Iron, filtered, micrograms per liter",
#     "p01049": "Lead, filtered, micrograms per liter",
#     "p01051": "Lead, unfiltered, recoverable, micrograms per liter",
#     "p01055": "Manganese, unfiltered, recoverable, micrograms per liter",
#     "p01056": "Manganese, filtered, micrograms per liter",
#     "p01090": "Zinc, filtered, micrograms per liter",
#     "p01092": "Zinc, unfiltered, recoverable, micrograms per liter",
#     "p29801": "Alkalinity, filtered, fixed endpoint (pH 4.5) titration, laboratory, mg/L as calcium carbonate",
#     "p30209": "Discharge, instantaneous, cubic meters per second",
#     "p50015": "Transit rate, sampler, feet per second",
#     "p50280": "Site visit purpose, code",
#     "p63676": "Turbidity, unfiltered, broad band light source (400-680 nm), detectors at multiple angles including 90 +-30 degrees, ratiometric correction, NTRU",
#     "p70301": "Dissolved solids, filtered, sum of constituents, mg/L",
#     "p70302": "Dissolved solids, short tons per day",
#     "p70303": "Dissolved solids, filtered, short tons per acre-foot",
#     "p70331": "Suspended sediment, sieve diameter, percent smaller than 0.0625 millimeters",
#     "p72219": "Sampler nozzle material, code",
#     "p72220": "Sampler nozzle diameter, code",
#     "p80154": "Suspended sediment concentration, mg/L",
#     "p80155": "Suspended sediment discharge, short tons per day",
#     "p82398": "Sampling method, code",
#     "p84164": "Sampler type, code",
#     "p84171": "Sample splitter type, field, code",
#     "p84182": "Bottle or bag sampler material (construction), code",
#     "p90095": "Specific conductance, unfiltered, laboratory, microsiemens per centimeter at 25 degrees Celsius",
#     "p91157": "Suspended sediment, sediment mass recovered from whole water sample, dry weight, grams",
#     "p91165": "Suspended sediment, between 0.063 and 4 mm sieve diameter, sediment mass analyzed for particle size fractions, dry weight, grams",
#     "p99105": "Type of replicate, code",
#     "p99111": "Type of quality assurance data associated with sample, code",
#     "p99156": "Sulfuric acid NWIS lot number, 4.5 N (1:7), 1 mL, National Field Supply Service (NFSS) stock number Q438FLD",
#     "p99159": "Nitric acid NWIS lot number, 7.5-7.7 N, 2 mL, National Field Supply Service (NFSS) stock number Q436FLD",
#     "p99161": "Conductance standard NWIS lot number, 100 uS/cm KCl, National Field Supply Service (NFSS) stock number Q43FLD",
#     "p99163": "Conductance standard NWIS lot number, 500 uS/cm KCl, National Field Supply Service (NFSS) stock number Q45FLD",
#     "p99164": "Conductance standard NWIS lot number, 750 uS/cm KCl, National Field Supply Service (NFSS) stock number Q46FLD",
#     "p99171": "pH 10 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q122FLD, Q123FLD",
#     "p99172": "pH 4 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q124FLD, Q125FLD",
#     "p99173": "pH 7 Buffer solution, NWIS lot number, National Field Supply Service (NFSS) stock numbers Q126FLD, Q127FLD",
#     "p99206": "NWIS lot number, capsule filter, 0.45 micron",
#     "p99870": "Julian date, in-bottle digestion, ddd",
# }
